### ISSUE TITLE
Split homebrew install to its own

### ISSUE THREAD

**Issue by mstibbard** [hjoshi123/M1DevSetup#4]
I've just done a factory reset of my M1 and have decided to give this a go.

**System:**
macOS Big Sur 11.3.1 (20E241)

**Steps executed:**
1. `xcode-select --install`
2. `zsh prereq.sh`
3. `zsh deps_part1.sh`

**Result:**
Homebrew installs successfully.
All other scripts fail with message that `brew` command doesn't exist.

**Suggestion:**
Split everything other than homebrew install into a separate dependencies install file?
The instructions can then be updated to open a new terminal / refresh the $PATH

**Comment by hjoshi123** [comment]
@mstibbard Would it work if `source ~/.zshrc` is added after the install in lieu of separating the install files?

**Comment by mstibbard** [comment]
Yes that would be smarter. 

This is probably a topic for a different GitHub Issue, but my thinking was that moving forward you might want to make it customizable (e.g. deps1 everyone does, then run any others you want such as deps-webdev etc etc)

**Comment by hjoshi123** [comment]
@mstibbard Could you create a different issue for this? The requirement makes a lot of sense.. But it would be good if you could suggest different categories which we could look into

**Comment by hjoshi123** [comment]
@mstibbard Added the path refresh.. Closing this issue and creating new one for separation of installs
